Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -23,4 +23,4 @@ jobs:
       run: |
         echo "reviewing the format with black from Python"
         black --check $(git ls-files '*.py')
-        if [ "$?" -eq "0" ]; then echo "format is ok"; then exit 1; fi
+        if [ "$?" -eq "0" ]; then echo "succes"; else echo "fails"; fi
